
INSERT INTO T_HN_Main
           (
            ProjCode
           ,ProjName
           ,ProjStatus
           ,BusinessType
           ,EngineeringCategories
           ,EngineeringType
           ,RoleType
           ,ProjType)
     VALUES
           (
            {PI_ProjCode}
           ,{PI_ProjName}
           ,'0'
           ,''
           ,''
           ,{PI_ProjType}
           ,'1'
           ,'0');

INSERT INTO T_HN_Main_ProjInfo
           (
			mainid
           ,maintbl
           ,subodr
           ,PI_ProjName
           ,PI_ProjCode
           ,PI_Province
           ,PI_City
           ,PI_District
           ,PI_Address
           ,PI_ProjType
           ,PI_ConPermissionNo
           ,PI_ConChargeDepartment
           ,PI_ChargeDepartmentTel
           ,PI_ConUnit
           ,PI_Director
           ,PI_DirectorTel
           ,PI_ProjectContact
           ,PI_ProjectContactTel
           ,PI_IsKeyProj
           ,PI_GovInvestmentProj
           ,PI_ConInvestmentNature
           ,PI_ConstructionNature
           ,PI_ProjPurpose
           ,PI_ApplyForContent
           ,PI_ConSurveyScale
           ,PI_ConTotalAmount
           ,PI_CensorshipAmount
           ,PI_RockConSurveyLevel
           ,PI_SurveyDate
           ,PI_DrillingTotalLength
           ,PI_ReformDepartmentPermissionNo
           ,PI_MainConstructionContent)
     VALUES
           (
           IDENT_CURRENT('T_HN_Main ')
           ,'T_HN_Main'
           ,''
           ,{PI_ProjName}
           ,{PI_ProjCode}
           ,{PI_Province}
           ,{PI_City}
           ,{PI_District}
           ,{PI_Address}
           ,{PI_ProjType}
           ,{PI_ConPermissionNo}
           ,{PI_ConChargeDepartment}
           ,{PI_ChargeDepartmentTel}
           ,{PI_ConUnit}
           ,{PI_Director}
           ,{PI_DirectorTel}
           ,{PI_ProjectContact}
           ,{PI_ProjectContactTel}
           ,{PI_IsKeyProj}
           ,{PI_GovInvestmentProj}
           ,{PI_ConInvestmentNature}
           ,{PI_ConstructionNature}
           ,{PI_ProjPurpose}
           ,{PI_ApplyForContent}
           ,{PI_ConSurveyScale}
           ,{PI_ConTotalAmount}
           ,{PI_CensorshipAmount}
           ,{PI_RockConSurveyLevel}
           ,{PI_SurveyDate}
           ,{PI_DrillingTotalLength}
           ,{PI_ReformDepartmentPermissionNo}
           ,{PI_MainConstructionContent});



INSERT INTO T_HN_Main_SurveyDesignUnit
           (
           mainid
           ,maintbl
           ,subodr
           ,SD_SurveyDesignUnitName
           ,SD_DesignContent
		   ,SD_QualificationNo
           ,SD_LegalRepresentative
		   ,SD_LegalRepIDCard
           ,SD_Contacts
           ,SD_QualificationType
           ,SD_QualificationLevel
           ,SD_ContactsTel
           ,SD_ProjDirector
		   ,SD_DirectorIDCard
           ,SD_DirectorRegQualification
           ,SD_DirectorSealRegID
           ,SD_CertifiedArchitect
           ,SD_CertifiedArchitectSealRegID
           ,SD_RegStructuralEngineer
           ,SD_RegSESealRegID)
     VALUES
           (
           IDENT_CURRENT('T_HN_Main ')
           ,'T_HN_Main'
           ,''
           ,{SD_SurveyDesignUnitName}
           ,{SD_DesignContent}
		   ,{SD_QualificationNo}
           ,{SD_LegalRepresentative}
		   ,{SD_LegalRepIDCard}
           ,{SD_Contacts}
           ,{SD_QualificationType}
           ,{SD_QualificationLevel}
           ,{SD_ContactsTel}
           ,{SD_ProjDirector}
		   ,{SD_DirectorIDCard}
           ,{SD_DirectorRegQualification}
           ,{SD_DirectorSealRegID}
           ,{SD_CertifiedArchitect}
           ,{SD_CertifiedArchitectSealRegID}
           ,{SD_RegStructuralEngineer}
           ,{SD_RegSESealRegID});

INSERT INTO T_HN_Main_CensorshipInfo
           (
           mainid
           ,maintbl
           ,subodr
           ,CI_ReviewUnitName
           ,CI_ReviewContent
           ,CI_QualificationType
           ,CI_LegalRepresentative
           ,CI_Contacts
           ,CI_QualificationLevel
           ,CI_LegalRepresentativeTel
           ,CI_ContactsTel
           ,CI_ProjDirector
           ,CI_DirectorRegQualification
           ,CI_DirectorSealRegID
           ,CI_CertifiedArchitect
           ,CI_CertifiedArchitectSealRegID
           ,CI_RegStructuralEngineer
           ,CI_RegSESealRegID)
     VALUES
           (
           IDENT_CURRENT('T_HN_Main ')
           ,'T_HN_Main'
           ,''
           ,{CI_ReviewUnitName}
           ,{CI_ReviewContent}
           ,{CI_QualificationType}
           ,{CI_LegalRepresentative}
           ,{CI_Contacts}
           ,{CI_QualificationLevel}
           ,{CI_LegalRepresentativeTel}
           ,{CI_ContactsTel}
           ,{CI_ProjDirector}
           ,{CI_DirectorRegQualification}
           ,{CI_DirectorSealRegID}
           ,{CI_CertifiedArchitect}
           ,{CI_CertifiedArchitectSealRegID}
           ,{CI_RegStructuralEngineer}
           ,{CI_RegSESealRegID});

INSERT INTO T_HN_Main_BuildingInfo
           (
           mainid
           ,maintbl
           ,subodr
           ,BI_CensorshipArea
           ,BI_AbovegroundArea
           ,BI_IsBuildingEnergySaving
           ,BI_IsHaveGreenBuilding
           ,BI_GreenBuildingArea
           ,BI_SeismicFortifyTurnProve
           ,BI_FortificationIntensity
           ,BI_IsOverrunHighrise
           ,BI_IsGreenProject
           ,BI_AssemblyRate
           ,BI_AssemblyArea
          )
     VALUES
           (
           IDENT_CURRENT('T_HN_Main ')
           ,'T_HN_Main'
           ,''
           ,{BI_CensorshipArea}
           ,{BI_AbovegroundArea}
           ,{BI_IsBuildingEnergySaving}
           ,{BI_IsHaveGreenBuilding}
           ,{BI_GreenBuildingArea}
           ,{BI_SeismicFortifyTurnProve}
           ,{BI_FortificationIntensity}
           ,{BI_IsOverrunHighrise}
           ,{BI_IsGreenProject}
           ,{BI_AssemblyRate}
           ,{BI_AssemblyArea}
           );

INSERT INTO T_HN_Main_SingleBidSection
           (
            mainid
           ,maintbl
           ,subodr
           ,BS_BuildingName
           ,BS_No
           ,BS_ConType
           ,BS_BuildingArea
           ,BS_AbovegroundFloors
           ,BS_UndergroundFloors
           ,BS_HighOrDeepBuried
           ,BS_StructureType
           ,BS_BasicForm
           )
     VALUES
           (
           IDENT_CURRENT('T_HN_Main ')
           ,'T_HN_Main'
           ,''
           ,{BS_BuildingName}
           ,{BS_No}
           ,{BS_ConType}
           ,{BS_BuildingArea}
           ,{BS_AbovegroundFloors}
           ,{BS_UndergroundFloors}
           ,{BS_HighOrDeepBuried}
           ,{BS_StructureType}
           ,{BS_BasicForm}
           );

SELECT IDENT_CURRENT('T_HN_Main ') AS mainid

